name: Deploy Blog

on:
  push:
    branches:
      - main

# ⭐ 防重复部署（关键）
concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          echo "USER=${SERVER_USER} HOST=${SERVER_HOST}"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 "${SERVER_USER}@${SERVER_HOST}" "cd ~/projects && whoami && pwd && ls -la && bash deploy.sh"
