name: Deploy Blog

on:
  push:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 修复本地仓库sh换行
      - name: Fix shell line break
        run: sed -i 's/\r$//' *.sh

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # 如果你有同步代码步骤保留，没有就删掉
      # - name: Sync code to server
      #   run: |
      #     rsync -avz --delete \
      #       -e "ssh -i ~/.ssh/id_ed25519" \
      #       ./ \
      #       admin@${{ secrets.SERVER_HOST }}:/home/admin/projects/

      - name: Deploy to Server
        env:
          REMOTE_CMD: cd /home/admin/projects && ls -la && sed -i 's/\r$//' deploy.sh && bash deploy.sh
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/id_ed25519 \
            admin@${{ secrets.SERVER_HOST }} \
            bash -c "$REMOTE_CMD"